from django.contrib import admin
from django.urls import path,include
from .views import (
    home,
    login_page,
    logout_view,
    firebase_login,
    profile_view,
    user_profile_view,
    verify_phone_token,
    add_task,
    take_task,
    complete_task,
    my_tasks,
    start_chat,
    chat_view,
    send_message,
    user_list,
    friends_view,
    send_friend_request,
    accept_friend_request,
    decline_friend_request,
    notifications_view,
)

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_page, name='login_page'),
    path('logout/', logout_view, name='logout'),
    path('firebase-login/', firebase_login, name='firebase_login'),
    path('profile/', profile_view, name='profile'),
    path('user/<int:user_id>/', user_profile_view, name='user_profile'),
    path('verify-phone-token/', verify_phone_token, name='verify_phone_token'),
    path('add_task/', add_task, name='add_task'),
    path('task/take/<int:task_id>/', take_task, name='take_task'),
    path('task/complete/<int:task_id>/', complete_task, name='complete_task'),
    path('my_tasks/', my_tasks, name='my_tasks'),
    path('chat/start/<int:user_id>/', start_chat, name='start_chat'),
    path('chat/<int:conversation_id>/', chat_view, name='chat_view'),
    path('chat/send/<int:conversation_id>/', send_message, name='send_message'),
    path('users/', user_list, name='user_list'),
    path('friends/', friends_view, name='friends'),
    path('friend/send/<int:user_id>/', send_friend_request, name='send_friend_request'),
    path('friend/accept/<int:request_id>/', accept_friend_request, name='accept_friend_request'),
    path('friend/decline/<int:request_id>/', decline_friend_request, name='decline_friend_request'),
    path('notifications/', notifications_view, name='notifications'),
]
