# Generated by Django 5.2.7 on 2025-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
