# Generated by Django 5.2.7 on 2025-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
    ]
