# Generated by Django 5.2.7 on 2025-10-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_friendrequest_closeness_alter_friendship_closeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from_user', to='basic.userprofile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_to_user', to='basic.userprofile'),
        ),
    ]
