# Generated by Django 5.2.7 on 2025-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_userprofile_rewards_alter_friendship_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='incentive',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rewards',
            field=models.IntegerField(default=1500),
        ),
    ]
