# Generated by Django 5.2.7 on 2025-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_remove_task_incentive_task_is_completed_task_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
