# Generated by Django 5.2.7 on 2025-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_userprofile_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instagram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
