# Generated by Django 5.2.7 on 2025-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
