# Generated by Django 5.2.7 on 2025-10-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_alter_conversation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_instagram_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
