# Generated by Django 5.2.7 on 2025-10-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_remove_friendrequest_closeness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.IntegerField(default=2029),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='basic.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_instagram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(default=1500, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeness', models.IntegerField(default=50)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from_user', to='basic.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_to_user', to='basic.userprofile')),
            ],
        ),
    ]
