# Generated by Django 5.2.7 on 2025-10-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_friendrequest_closeness_userprofile_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_instagram_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
