# Generated by Django 5.2.7 on 2025-10-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='task',
        ),
    ]
