# Generated by Django 5.2.7 on 2025-10-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_conversation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.IntegerField(default=2029),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_instagram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
    ]
