# Generated by Django 5.2.7 on 2025-10-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_friendrequest_closeness_userprofile_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
    ]
