# Generated by Django 5.2.7 on 2025-10-07 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0027_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
