# Generated by Django 5.2.7 on 2025-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0029_remove_task_is_completed_remove_task_is_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
