# Generated by Django 5.2.7 on 2025-10-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0030_task_cancellation_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cancellation_requested',
        ),
    ]
