# Generated by Django 5.2.7 on 2025-10-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0032_disputechatmessage_disputevote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disputevote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disputevote',
            name='dispute',
        ),
        migrations.RemoveField(
            model_name='disputevote',
            name='voted_for',
        ),
        migrations.RemoveField(
            model_name='disputevote',
            name='voter',
        ),
        migrations.DeleteModel(
            name='DisputeChatMessage',
        ),
        migrations.DeleteModel(
            name='DisputeVote',
        ),
    ]
