# Generated by Django 5.2.7 on 2025-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0033_alter_disputevote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
