# Generated by Django 5.2.7 on 2025-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0034_task_cancellation_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(choices=[('payment', 'Payment Issue'), ('quality', 'Quality of Work'), ('communication', 'Communication Breakdown'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
