# Generated by Django 5.2.7 on 2025-10-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0036_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
    ]
