# Generated by Django 5.2.7 on 2025-10-14 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0037_remove_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('task_chat', 'Task Chat'), ('bid_chat', 'Bid Chat'), ('general_chat', 'General Chat')], default='general_chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='basic.task'),
        ),
    ]
