# Generated by Django 5.2.7 on 2025-10-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0038_remove_friendrequest_closeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
    ]
