# Generated by Django 5.2.7 on 2025-10-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0039_remove_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='dispute_type',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='basic.task'),
        ),
    ]
