# Generated by Django 5.2.7 on 2025-10-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0040_remove_dispute_dispute_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(choices=[('payment', 'Payment Issue'), ('quality', 'Quality of Work'), ('communication', 'Communication Breakdown'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='closeness',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.task'),
        ),
    ]
