# Generated by Django 5.2.7 on 2025-10-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0041_dispute_dispute_type_friendrequest_closeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='dispute_type',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='basic.task'),
        ),
    ]
